### ISSUE TITLE
ModuleNotFoundError: No module named 'MySQL'

### ISSUE THREAD

**Issue by Radis35** [Ailothaen/linky#1]
Bonjour, lorsque je lance le script linky.py j'ai ce message d'erreur : ModuleNotFoundError: No module named 'MySQLdb'

J'ai pourtant bien suivi les étapes du tuto. Qu'ai-je pu louper ? Je suis sur un Pi Zero sous Raspbian.

**Comment by Ailothaen** [comment]
Bonjour,
Cette erreur dit que la bibliothèque d'interaction avec MySQL n'est pas installée.
Est-ce que la commande `python3 -m pip install -r requirements.txt` a bien été faite ? (elle est normalement censée installer `mysqlclient` depuis PyPI)
Aussi, il faut faire attention à bien utiliser Python 3 (et la même version) quand on lance `linky.py`.

**Comment by Radis35** [comment]
J'ai pourtant bien exécuté ces commandes. je vais réessayer ce soir. 
merci pour la réponse.

**Comment by Radis35** [comment]
Le premier problème est resolu. Cependant maintenant lorsque je lance le script j'obtiens ceci

-- Journal begins at Wed 2023-05-03 02:36:12 CEST, ends at Tue 2023-10-03 22:45:35 CEST. --
Oct 03 22:40:51 raspberrypi systemd[1]: Started Python service fetching Linky and putting data into MySQL.
Oct 03 22:40:52 raspberrypi python3[14173]: Traceback (most recent call last):
Oct 03 22:40:52 raspberrypi python3[14173]:   File "/srv/linky/main.py", line 7, in <module>
Oct 03 22:40:52 raspberrypi python3[14173]:     import linky
Oct 03 22:40:52 raspberrypi python3[14173]:   File "/srv/linky/linky.py", line 180, in <module>
Oct 03 22:40:52 raspberrypi python3[14173]:     log = init_log_system()
Oct 03 22:40:52 raspberrypi python3[14173]:   File "/srv/linky/linky.py", line 16, in init_log_system
Oct 03 22:40:52 raspberrypi python3[14173]:     handler = logging.handlers.RotatingFileHandler('./logs/linky.log', maxByt>
Oct 03 22:40:52 raspberrypi python3[14173]:   File "/usr/lib/python3.9/logging/handlers.py", line 153, in __init__
Oct 03 22:40:52 raspberrypi python3[14173]:     BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
Oct 03 22:40:52 raspberrypi python3[14173]:   File "/usr/lib/python3.9/logging/handlers.py", line 58, in __init__
Oct 03 22:40:52 raspberrypi python3[14173]:     logging.FileHandler.__init__(self, filename, mode=mode,
Oct 03 22:40:52 raspberrypi python3[14173]:   File "/usr/lib/python3.9/logging/__init__.py", line 1142, in __init__
Oct 03 22:40:52 raspberrypi python3[14173]:     StreamHandler.__init__(self, self._open())
Oct 03 22:40:52 raspberrypi python3[14173]:   File "/usr/lib/python3.9/logging/__init__.py", line 1171, in _open
Oct 03 22:40:52 raspberrypi python3[14173]:     return open(self.baseFilename, self.mode, encoding=self.encoding,
Oct 03 22:40:52 raspberrypi python3[14173]: FileNotFoundError: [Errno 2] No such file or directory: '/srv/linky/logs/link>
Oct 03 22:40:53 raspberrypi systemd[1]: linky.service: Main process exited, code=exited, status=1/FAILURE
Oct 03 22:40:53 raspberrypi systemd[1]: linky.service: Failed with result 'exit-code'.
Oct 03 22:40:53 raspberrypi systemd[1]: linky.service: Consumed 1.567s CPU time.

Désolé je début sur Unix et encore plus en Python

**Comment by Ailothaen** [comment]
Le problème vient de là :
> Oct 03 22:40:52 raspberrypi python3[14173]: FileNotFoundError: [Errno 2] No such file or directory: '/srv/linky/logs/link>

Les logs sont créés dans un dossier "logs", qui n'est pas présent (en effet, je réalise que j'ai oublié de le mettre dans le dépôt...).
Il faut donc créer un dossier "logs" dans le même dossier que `linky.py`, après cela le script devrait se lancer correctement.

**Comment by Radis35** [comment]
merci pour vos réponses. J'ai bien un dossier logs pourtant.

root@raspberrypi:/srv/linky# ls
config.yml  linky.py  logs  main.py  __pycache__  requirements.txt


Le message d'erreur maintenant est : 
Oct 03 22:40:52 raspberrypi python3[14173]: FileNotFoundError: [Errno 2] No such file or directory: '/srv/linky/logs/linky.log'

Dois-je créer le fichier linky.log ?

**Comment by Radis35** [comment]
J'ai bien un dossier logs pourtant :

root@raspberrypi:/srv/linky# cd /srv/linky/logs
root@raspberrypi:/srv/linky/logs# ls
link  linky.log
root@raspberrypi:/srv/linky/logs# nano linky.log 
root@raspberrypi:/srv/linky/logs# journalctl -u linky
-- Journal begins at Wed 2023-05-03 02:36:12 CEST, ends at Wed 2023-10-04 21:22:21 CEST. --
Oct 03 22:40:51 raspberrypi systemd[1]: Started Python service fetching Linky and putting data into MySQL.
Oct 03 22:40:52 raspberrypi python3[14173]: Traceback (most recent call last):
Oct 03 22:40:52 raspberrypi python3[14173]:   File "/srv/linky/main.py", line 7, in <module>
Oct 03 22:40:52 raspberrypi python3[14173]:     import linky
Oct 03 22:40:52 raspberrypi python3[14173]:   File "/srv/linky/linky.py", line 180, in <module>
Oct 03 22:40:52 raspberrypi python3[14173]:     log = init_log_system()
Oct 03 22:40:52 raspberrypi python3[14173]:   File "/srv/linky/linky.py", line 16, in init_log_system
Oct 03 22:40:52 raspberrypi python3[14173]:     handler = logging.handlers.RotatingFileHandler('./logs/linky.log', maxBytes=10000>
Oct 03 22:40:52 raspberrypi python3[14173]:   File "/usr/lib/python3.9/logging/handlers.py", line 153, in __init__
Oct 03 22:40:52 raspberrypi python3[14173]:     BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
Oct 03 22:40:52 raspberrypi python3[14173]:   File "/usr/lib/python3.9/logging/handlers.py", line 58, in __init__
Oct 03 22:40:52 raspberrypi python3[14173]:     logging.FileHandler.__init__(self, filename, mode=mode,
Oct 03 22:40:52 raspberrypi python3[14173]:   File "/usr/lib/python3.9/logging/__init__.py", line 1142, in __init__
Oct 03 22:40:52 raspberrypi python3[14173]:     StreamHandler.__init__(self, self._open())
Oct 03 22:40:52 raspberrypi python3[14173]:   File "/usr/lib/python3.9/logging/__init__.py", line 1171, in _open
Oct 03 22:40:52 raspberrypi python3[14173]:     return open(self.baseFilename, self.mode, encoding=self.encoding,
Oct 03 22:40:52 raspberrypi python3[14173]: FileNotFoundError: [Errno 2] No such file or directory: '/srv/linky/logs/linky.log'
Oct 03 22:40:53 raspberrypi systemd[1]: linky.service: Main process exited, code=exited, status=1/FAILURE
Oct 03 22:40:53 raspberrypi systemd[1]: linky.service: Failed with result 'exit-code'.
Oct 03 22:40:53 raspberrypi systemd[1]: linky.service: Consumed 1.567s CPU time.
-- Boot 12578df9e0ce45f5b8511d66a864d8ff --
Oct 04 21:13:38 raspberrypi systemd[1]: Started Python service fetching Linky and putting data into MySQL.
Oct 04 21:13:50 raspberrypi python3[483]: Something went wrong while opening config file. See logs for more info.
Oct 04 21:13:51 raspberrypi systemd[1]: linky.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Oct 04 21:13:51 raspberrypi systemd[1]: linky.service: Failed with result 'exit-code'.
Oct 04 21:13:51 raspberrypi systemd[1]: linky.service: Consumed 1.694s CPU time.

**Comment by Radis35** [comment]
ok, j'avance :)

maintenant j'en suis la dans les log :)

  GNU nano 5.4                                                 linky.log *                                                        
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 58, in compose_document
    self.get_event()
  File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 118, in get_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "/usr/local/lib/python3.9/dist-packages/yaml/scanner.py", line 129, in peek_token
    self.fetch_more_tokens()
  File "/usr/local/lib/python3.9/dist-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/usr/local/lib/python3.9/dist-packages/yaml/scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "config.yml", line 2, column 9
[2023-10-04 21:53:29 +0200][main][DEBUG] Loading config...
[2023-10-04 21:53:30 +0200][main][DEBUG] Config loaded! Values: {'database': {'server': 'localhost:3036', 'name': 'linky', 'user'>
[2023-10-04 21:53:30 +0200][linky][CRITICAL] Something went wrong while connecting to database server:
Traceback (most recent call last):
  File "/srv/linky/linky.py", line 99, in open_db
    db = MySQLdb.connect(server, user, password, name)
  File "/usr/local/lib/python3.9/dist-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/MySQLdb/connections.py", line 193, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2005, "Unknown MySQL server host 'localhost:3036' (-2)")
[2023-10-04 21:56:07 +0200][main][DEBUG] Loading config...
[2023-10-04 21:56:07 +0200][main][DEBUG] Config loaded! Values: {'database': {'server': 'localhost:3036', 'name': 'linky', 'user'>
[2023-10-04 21:56:07 +0200][linky][CRITICAL] Something went wrong while connecting to database server:
Traceback (most recent call last):
  File "/srv/linky/linky.py", line 99, in open_db
    db = MySQLdb.connect(server, user, password, name)
  File "/usr/local/lib/python3.9/dist-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/MySQLdb/connections.py", line 193, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2005, "Unknown MySQL server host 'localhost:3036' (-2)")

**Comment by Radis35** [comment]
ok j'avance, j'ai l'impression que ça fonctionne ne partie. Dans les logs j'ai bien les infos qui remonte du linky. 

Mais par contre je n'arrive pas à lire la base avec la commande select * from stream

[2023-10-04 22:19:55 +0200][main][DEBUG] Loading config...
[2023-10-04 22:19:55 +0200][main][DEBUG] Config loaded! Values: {'database': {'server': '127.0.0.1', 'name': 'linky', 'user': 'xxxxx', 'password': 'xxxxxxx!'}, 'devi>
[2023-10-04 22:19:55 +0200][linky][INFO] Database schema is not there, creating it...
[2023-10-04 22:19:57 +0200][linky][INFO] Database schema created successfully
[2023-10-04 22:19:57 +0200][main][DEBUG] Cycle begins
[2023-10-04 22:19:57 +0200][main][DEBUG] Opening terminal...
[2023-10-04 22:19:57 +0200][main][DEBUG] Current line: ^@^@IF BBR( S

[2023-10-04 22:19:57 +0200][main][DEBUG] Current line: ISOUSC 60 <

[2023-10-04 22:19:58 +0200][main][DEBUG] Current line: BBRHCJB 052185310 6

[2023-10-04 22:19:58 +0200][main][DEBUG] Current line: BBRHPJB 049675934 Y

[2023-10-04 22:19:58 +0200][main][DEBUG] Current line: BBRHCJW 000000000 2

[2023-10-04 22:19:58 +0200][main][DEBUG] Current line: BBRHPJW 000000000 ?

[2023-10-04 22:19:58 +0200][main][DEBUG] Current line: BBRHCJR 000000000 -

[2023-10-04 22:19:58 +0200][main][DEBUG] Current line: BBRHPJR 000000000 :

[2023-10-04 22:19:59 +0200][main][DEBUG] Current line: PTEC HCJB C

[2023-10-04 22:19:59 +0200][main][DEBUG] Current line: DEMAIN ---- "

[2023-10-04 22:19:59 +0200][main][DEBUG] Current line: IINST 004 [

**Comment by Radis35** [comment]
MariaDB [(none)]> use linky
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [linky]> select * from stream;
Empty set (0.004 sec)

MariaDB [linky]>

**Comment by Ailothaen** [comment]
Salut,

Est-ce que tu as pu résoudre le problème depuis le dernier message ?

Sinon, qu'est-ce que tu vois dans le fichier de logs ? Est-ce que le service tourne correctement ?

**Comment by Radis35** [comment]
le service tourne visiblement. 

Mon avant dernier message sont les données dans linky.log. On y voit les données du linky. 

Pas d'erreur remontée ni dans les logs ni dans le journal du service. 

Par contre rien dans la db. comme le montre mon dernier message. 

Je ne comprends pas 🙃

**Comment by Radis35** [comment]
Dans le journalctl -u Linky j'ai ceci :

**Comment by Radis35** [comment]
Quand je tape la commande journalctl -u linky j'ai ceci : 

-- Boot a459d651eb52479faf3feef8fc0e4229 --
Oct 04 21:53:18 raspberrypi systemd[1]: Started Python service fetching Linky and putting data into MySQL.

**Comment by jlebonzec** [comment]
Hello, il semble que le code ne soit pas compatible avec le forfait Heure Creuses.

Voici un extrait de mon picocom (`sudo picocom -b 1200 -d 7 -f n /dev/ttyS0`) :
```
OPTARIF HC.. <
ISOUSC 45 ?
HCHC 012980129 &
HCHP 01596693 =
PTEC HP..
IINST 009
IMAX 090 H
PAPP 02050 (
...
```

Comparé à celui du blog :
```
OPTARIF BASE 0
ISOUSC 30 9
BASE 002078240 "
PTEC TH.. $
IINST 000 W
IMAX 090 H
PAPP 00070 (
...
```

On peut voir que j'ai le tarif HC HP, et le Linky m'envoie les décomptes respectifs sur `HCHC` et `HCHP`. Avec le forfait Base, un seul décompte est donné, via le mot `BASE`.

La ligne OPTARIF indique le type de forfait utilisé. Le code de ce GitHub part du principe que le forfait base est celui utilisé, et récupère le relevé de compteur via le mot `BASE`. 
https://github.com/Ailothaen/linky/blob/fd81723abdcd579dafa84351a89b789670dbc03c/main.py#L56-L57

[Cette documentation d'ENEDIS (attention télécharment de PDF)](https://www.enedis.fr/media/2027/download) devrait être utile pour supporter davantage de cas. On y remarque notamment que dans le cas du tarif Tempo, que tu dois avoir @Radis35, si j'en crois la présence des `BBRHCJB` (relevé HC Jour Bleu) et `DEMAIN` (couleur du jour de demain)

Je pense qu'il est nécessaire de modifier une partie du code responsable des injections en BDD notamment. Avec un peu de chance, j'aurais le temps de me pencher dessus dans les prochaines semaines, au mois pour le tarif HC HP.

**Comment by Radis35** [comment]
Hello, merci pour ce retour. J'ai en effet progressé (merci Chat GPT) et j'ai réussi à coder un truc qui tourne maintenant depuis quelques semaines.

J'ai mis ça ici, fortement insipiré de ce tuto et d'un autre.

https://github.com/Radis35/Teleinfo-Linky-TEMPO

**Comment by Ailothaen** [comment]
Bonjour tout le monde,

Ah oui, en effet, en lisant vos messages, je m'aperçois que je n'ai pas du tout pensé aux heures creuses, ni aux jours Tempo 😇

Oui, je pourrais sûrement faire des modifications du programme pour prendre en compte ces cas.  
Cependant, je me demande comment l'énergie serait alors comptée : dans une seule colonne comme actuellement, ou deux pour les compteurs HP/HC (voire six dans le cas du Tempo)? Ou les deux ? Quels seraient vos avis ?

**Comment by comdif** [comment]
Quelle perte de temps Python, j'ai finis avec un "future feature annotations is not defined", bien sur on a jamais la bonne version :-)
Tant pis j'ai pas envie d'upgrader ma distro, je vais le re écrire en script shell.

**Comment by comdif** [comment]
J'ai finalement fait marcher le système, sacré travail, surtout que a la base je n'y connais rien a Python !
Vu que j'ai un compteur HP/HC j'ai du complètement bidouiller le script, ma table stream est maintenant:

ccr.execute("CREATE TABLE `stream` (`id` int(20) UNSIGNED NOT NULL,`clock` datetime NOT NULL,`HCHP` int(11),`HCHC` int(11),`PAPP` int(11),`PTEC` varchar(11),`HCHP_diff` int(11),`HCHC_diff` int(11))

J'ai rajouté le champ varchar PTEC pour savoir si on est en heure creuse ou pas.
 comme ce n'est pas un nombre il faut bien penser a mettre
        if line.startswith('PTEC'):
           data_PTEC = str(line[5:7])
   
Bah sinon c'est pas compliqué quand on sais, remplacer dans le script tous les "BASE" par des "HCHP" et ajouter les "HCHC"

<img width="1598" height="433" alt="Image" src="https://github.com/user-attachments/assets/8d826eb3-3c93-4d94-b7c1-86287eff8604" />

Le pic c'est la Senseo, ca bouffe ce truc :-(
Je forkerais quand j'aurais tout bien finis !

**Comment by jlebonzec** [comment]
Bonjour, merci pour ton retour !

En général ce genre de repository, on le met à jour quand on est dans la bidouille  mais après on le laisse dans son coin, donc je ne pense pas qu'Ailothaen le mettra à jour (surtout qu'il fonctionne très bien dans le cas d'un contrat fixe !)
Cela dit ça aide beaucoup les autres utilisateurs donc c'est une bonne pratique !

Si ça intéresse certains, j'ai fais un fork sur mon profil et j'ai pas mal retravaillé le code de sorte à supporter les contrats fixes, HPHC, et Tempo. J'ai aussi trouvé que le script initial finissait par mettre à genoux mon RPi à cause des requêtes SQL de Grafana, du coup j'ai créé des tables annexes pour les données archivées.

Ça implique un peu plus de connaissances pour la partie Grafana en revanche.

Là je regarde pour faire un script qui analyserait les consommations de l'année et me dirait quel contrat aurait été le moins onéreux parmi une liste configurée.

**Comment by comdif** [comment]
@jlebonzec Merci pour tes précisions, je fait tourner ça sur mon petit serveur ESXI et une VM Ubuntu 24LTS ( petite précision python3 -m pip install -r requirements.txt ca ne marche pas sur cette distro, il faut les installer a la mano avec APT ) donc pas de problèmes de ressources machine.
je n'ai pas vu sur ton Fork les Options HPHC ?
Sinon Grafana c'était pour le fun, je compte faire mon dashboard en PHP (la je m'y connais).

**Comment by Ailothaen** [comment]
Je suis bien toujours là :)  
En effet, j'avais l'intention d'améliorer les scripts pour qu'ils soient aussi compatibles avec les contrats HC/HP, Tempo et EJP. Je ne pourrai pas les tester, mais bon, je ne pense pas que c'est nécessaire, étant donné que la seule chose qui change est l'index à regarder (qui est bien documenté)

Je ferai sûrement la modif dans les prochains jours, par contre je devrai du coup sûrement changer le schéma de la base de données (pour stocker aussi les index HC/HP et Tempo).  
Mais n'hésitez pas à proposer une pull request aussi, si vous avez fait d'autres améliorations.

> python3 -m pip install -r requirements.txt ca ne marche pas sur cette distro

J'imagine que c'est "à cause" des nouvelles sécurités de pip, qui empêchent d'installer des paquets Python sur un système qui utilise déjà Python et sur lequel il y a des risques de conflit.
Cela peut toutefois se résoudre facilement avec un virtualenv (un classique de Python), idem, je mettrai à jour le guide pour expliquer comment on fait.

**Comment by Ailothaen** [comment]
Je viens de publier une nouvelle version, qui ajoute le support des différents contrats (Base, HC/HP, Tempo, EJP), ainsi que du mode standard : https://github.com/Ailothaen/linky/releases/tag/v3.0.0

Le README a aussi été mis à jour, pour intégrer des précisions sur l'installation.

Je vais fermer cette issue étant donné que les problèmes initiaux sont résolus et que les améliorations ont été faites, n'hésitez pas à en créer d'autres si besoin !
